# Generated by Django 3.0.6 on 2020-05-15 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTitle', models.CharField(max_length=100)),
                ('articleContent', models.TextField()),
                ('articlePublishedBy', models.CharField(choices=[('arun kesavan', 'Arun Kesavan'), ('arivoli durai', 'Arivoli Durai'), ('rajesh veeraiyan', 'Rajesh Veeraiyan')], default='arun kesavan', max_length=100)),
                ('articlePublishedDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
