# Generated by Django 3.0.6 on 2020-05-15 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLibrary', '0002_remove_myreferences_articlepublishedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500)),
                ('article_content', models.TextField()),
                ('last_updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MyReferences',
        ),
    ]
