# Generated by Django 3.0.6 on 2020-05-17 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeLibrary', '0007_auto_20200517_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencebook',
            name='article_manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
