# Generated by Django 3.0.6 on 2020-05-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeLibrary', '0008_referencebook_article_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencebook',
            name='article_manager',
        ),
    ]
